---
version: '3.4'
services:
  besu_node:
    image: hyperledger/besu:latest
    container_name: besu
    user: 1003:1003
    restart: always
    command: ["--network=goerli",
              "--data-storage-format=BONSAI",
              "--data-path=/lw/data/besu",
              "--host-allowlist=*",
              "--sync-mode=X_SNAP",
              "--engine-rpc-enabled=true",
              "--engine-host-allowlist=*",
              "--engine-rpc-port=8551",
              "--engine-jwt-secret=jwtsecret",
              "--rpc-ws-enabled=true",
              "--rpc-ws-port=8546",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-http-enabled=true",
              "--rpc-http-port=8545",
              "--rpc-http-host=0.0.0.0"]
    volumes:
      - ./besu:/lw/data/besu
      - /lw/data/jwtsecret:/opt/besu/jwtsecret
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224

  teku_node:
    environment:
      - "JAVA_OPTS=-Xmx4g"
      - "TEKU_OPTS=-XX:-HeapDumpOnOutOfMemoryError"
    image: consensys/teku:latest
    container_name: teku
    user: 1004:1004
    restart: always
    command: ["--network=goerli",
              "--data-path=/lw/data/teku",
              "--ee-endpoint=http://besu_node:8551",
              "--initial-state=https://goerli.checkpoint-sync.ethdevops.io/eth/v2/debug/beacon/states/finalized",
              "--ee-jwt-secret-file=jwtsecret",
              "--p2p-port=9000"]
    depends_on:
      - besu_node
    volumes:
      - ./teku:/lw/data/teku
      - /lw/data/jwtsecret:/opt/teku/jwtsecret
    ports:
      # Map the p2p port(9000) and REST API port(5051)
      - "9000:9000/tcp"
      - "9000:9000/udp"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
